services:
  db:
    image: postgres:13
    restart: always
    env_file:
      - ../db.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_website-api:/var/lib/postgresql/data

  auth-api:
    image: busycaesar/auth-api:latest
    restart: always
    env_file:
      # All the variable related to db.
      - ../db.env
      # All the variables required by auth-api image.
      - ../auth-api.env
    # Docker compose will allow the containers declared to interact with each other using specified host name.
    environment:
      - POSTGRES_HOST: db
      - POSTGRES_PORT: 5432
    ports:
      - "7000:7000"
    depends_on:
      - db

volumes:
  postgres_website-api:
